const countries = [
  { title: "United States" },
  { title: "India" },
  { title: "Canada" },
  { title: "Australia" },
  { title: "Germany" },
  { title: "France" },
  { title: "Japan" },
  { title: "Brazil" },
  { title: "United Kingdom" },
  { title: "China" },
  { title: "Russia" },
  { title: "South Africa" },
  { title: "New Zealand" },
  { title: "Mexico" },
  { title: "Italy" },
  { title: "Spain" },
  { title: "Argentina" },
  { title: "South Korea" },
  { title: "Nigeria" },
  { title: "Egypt" },
  { title: "Turkey" },
  { title: "Saudi Arabia" },
  { title: "Indonesia" },
  { title: "Pakistan" },
  { title: "Bangladesh" },
  { title: "Vietnam" },
  { title: "Thailand" },
  { title: "Malaysia" },
  { title: "Singapore" },
  { title: "Philippines" },
  // Add more countries as needed
];


export default countries;